import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Footer from '../components/Footer'
import HeroSection from '../components/HeroSection'
import Work from '../components/Work'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Sergio Valbuena Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />


      <Link href="https://www.google.com">
        <div>
          
        <button>
      google    
      </button>
        </div>
       </Link>

      <div id="work">
        
        <Work/>
        
      </div>
      <Footer/>
      
    </div>
  )
}
